apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secret.apiKey | quote }}
  SLACK_BOT_TOKEN: {{ .Values.secret.slackBotToken | quote }}
  SLACK_APP_TOKEN: {{ .Values.secret.slackAppToken | quote }}
